FROM mcr.microsoft.com/dotnet/core/runtime:2.2.5-stretch

WORKDIR /app
COPY ./SunshineDownloader/app ./

RUN apt-get update
RUN apt-get install -y unzip procps
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg

ENTRYPOINT ["dotnet", "Sunshine.Downloader.dll"]