FROM mcr.microsoft.com/dotnet/core/runtime:2.2.5-stretch-arm32v7

WORKDIR /app
COPY ./bin/Release/netcoreapp2.2/publish ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "Sunshine.Downloader.dll"]