module Logo

let printLogo() =
    printfn """
MMMMMMMMMMMMMMMMMMMMNd:dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMO' .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNxco0WMMMM0' '0MMMMWKocxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNl. .lKMMMNOdONMMMXo. .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNO:.,OXko:,,;:lkX0;.:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWXKd'         'd0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMNl.            lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMNx::::dXO.             .kXd::::dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMXo'..'cKk.             .xXl'..'lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMWNNNNWMX:             :XMWNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWKl.         .lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWKo;cO0o:'...';o00c;oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNd.  :0MMWXkdkXWMMK:. .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNd,:kNMMMMK; ,0MMMMNk:,oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWWWMMMMMMO. .OMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMXl'lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kOKWMMMMMMMMMMMMMMNOkOXMMMMMMMMMMMMMWXOk0NMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;.  .oNMMMMMMMMMMWXd'   'kWMMMMMMMMMW0c.  .:KMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNk;.     ;KMMMMMMMMMXd'      lNMMMMMMMW0l.     .kMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNk;.     .:OWMMMMMMMXd'      .lXMMMMMMW0l.      'xNMMMMM
MMMMMMMMMMMMMMMMMMMMMMNO;.     .;kNMMMMMMWXd'      .lKWMMMMMW0l.      'dXWMMMMMM
MMMMMMMMMMMMMMMMMMMMNO:.     .;kNMMMMMMX0d'      .lKWMMMMMW0l.      'dXMMMMMMMMM
MMMMMMMMMMMMMMMMMMNO:.     .;kNMMMMMMXd'.      .l0WMMMMMW0l.      'dXMMMMMMMMMMM
MMMMMMMMMMMMMMMMNO:.       oNMMMMMMXd'        .kWMMMMMW0l.       :KMMMMMMMMMMMMM
MMMMMMMMMMMMMMNO:.        .kMMMMMXd'          ,KMMMMW0l.         oWMMMMMMMMMMMMM
MMMMMMMMMMMMWO:.          .xMMMXd'            ,KMMWKl.           oWMMMMMMMMMMMMM
MMMMMMMMMMMNo.      .     .xMMK:      ...     ,KMMO'      ..     oWMMMMMMMMMMMMM
MMMMMMMMMMMNc     ;kx.    .xMM0,    .c0d..    ,KMWx.    'dO;     oWMMMMMMMMMMMMM
MMMMMMMMMMMMXdc:lkNMO.    .xMMW0o::o0WMd..    ,KMMNkc:cxXWX:     oWMMMMMMMMMMMMM
MMWXOkkkkkkkkkxxxxkkl.    .cxxkkxxxxxkx:.     .okkkkxxxkkkd'     ;xkkkkkkkkOKWMM
MWk,                                                                        .dNM
MNl                                                                          ;KM
MMKo,'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''',cOWM
MMMMNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMM
    """